export const client = {
  name: "Forever Green Gardening Services Ltd",
  tagline: "Professional Gardening in Fleet — Quality You Can Trust",
  description: "Professional gardening services in Fleet and surrounding areas. Trusted local experts with 15 Google reviews.",
  category: "Gardening",
  yearEstablished: "2015",
  phone: "",
  email: "",
  website: "",
  address: "",
  city: "Fleet",
  county: "",
  postcode: "",
  basedIn: "Fleet",
  founderName: "",
  founderSurname: "",
  founderRole: "Director",
  facebook: "",
  instagram: "",
  linkedin: "",
  twitter: "",
  googleRating: "4.7",
  reviewCount: "15",
  services: [
    { title: "Garden Design", description: "Bespoke garden designs tailored to your lifestyle and space.", icon: "tree" },
    { title: "Landscaping", description: "Complete hard and soft landscaping to transform your outdoor area.", icon: "shovel" },
    { title: "Paving & Patios", description: "Beautiful paving solutions using premium natural stone and porcelain.", icon: "wall" },
    { title: "Planting Schemes", description: "Year-round colour and interest with expertly curated planting plans.", icon: "flower" },
  ],
  cinematic: {
    frameCount: 181, frameDir: "/frames/", framePrefix: "frame_", frameExtension: ".jpg",
    framePadding: 4, scrollLength: "500vh", mobileFrameCount: 181, mobileFrameDir: "/frames-mobile/",
    scrubSpeed: 0.5, heroStillImage: "/images/hero-still.jpg", heroStillImageMobile: "/images/hero-still-mobile.jpg",
  },
  beforeAfter: { beforeImage: "/images/before.jpg", afterImage: "/images/after.jpg", beforeLabel: "Current Garden", afterLabel: "Our Vision" },
  transformations: [
    { before: "/images/before.jpg", after: "/images/after.jpg", label: "Complete Garden Renovation" },
    { before: "/images/patio-before.jpg", after: "/images/patio-after.jpg", label: "Patio & Fencing" },
    { before: "/images/front-before.jpg", after: "/images/front-after.jpg", label: "Front Garden" },
    { before: "/images/lawn-before.jpg", after: "/images/lawn-after.jpg", label: "Lawn Restoration" },
    { before: "/images/fence-before.jpg", after: "/images/fence-after.jpg", label: "New Fencing" },
    { before: "/images/deck-before.jpg", after: "/images/deck-after.jpg", label: "Decking & Furniture" },
    { before: "/images/path-before.jpg", after: "/images/path-after.jpg", label: "Garden Path" },
    { before: "/images/border-before.jpg", after: "/images/border-after.jpg", label: "Planting Borders" },
    { before: "/images/drive-before.jpg", after: "/images/drive-after.jpg", label: "Driveway" },
  ] as { before: string; after: string; label: string }[],
  reviews: [
    { name: "Alan Perrett", rating: 5, text: "Ben and the team turned our chipped bark paths into gravel and replaced the edging poles that were rotting. The bigger part of the job was replacing the retaining walls in the garden that were softwood and had started to rot - they were replaced with oak and look fabulous. The curved design was retained which keeps the 'soft' feel of the garden. Not easy to do. There was an especially tricky bit where the walls wet behind the pond, but they managed to get those done without disturbing anything.", date: "3 months ago", badge: "Local Guide" },
    { name: "Malcolm Smy", rating: 5, text: "Ben and the team did fantastic work trimming all of our hedges. It was a large job but they did great, leaving everything neat and tidy. Cheers!", date: "5 months ago" },
    { name: "Michelle Cooper", rating: 5, text: "⭐️⭐️⭐️⭐️⭐️ I can’t recommend Benjamin and the team at Forever Gardening highly enough! They completely transformed my front garden and gave my back garden a fantastic tidy-up. The team were hard-working, reliable, and incredibly flexible, making the whole experience stress-free and enjoyable. Their attention to detail and care for the gardens really shows, and I’m thrilled with the results. Thank you so much for your amazing work!", date: "5 months ago" },
    { name: "Kathy Girard", rating: 5, text: "Ben and his team have done a fantastic job of renewing our decking in the back garden, they also laid artificial grass in the front, and did block paving on path.  We also use Ben and team for spring and winter garden prep.  They are a great team, punctual and tidy.  Ben constantly updates you on their progress, gives advice and also resolves any issues - can highly recommend!", date: "10 months ago" },
    { name: "John Boutal", rating: 5, text: "Had a fantastic experience with Ben and his team. We had quite a big garden renovation project, including laying decking, building a shed, building a retaining wall to expand our lawn. Everything was done to a high quality by high quality people. They had great suggestions, some of which we added to the project that really added to what we were doing. Highly recommended and will look to use again where we can!", date: "10 months ago" },
    { name: "Sid Ness", rating: 5, text: "Ben's team were great, did a great job! When there was an issue Ben happily resolved. Highly recommend!", date: "a year ago" },
  ] as { name: string; rating: number; text: string; date: string; badge?: string }[],
  seo: {
    title: "Forever Green Gardening Services Ltd | Professional Gardening in Fleet",
    description: "Professional gardening in Fleet. 4.7 stars on Google with 15 reviews. Quality workmanship guaranteed.",
  },
};
